
# 一级用户自定义配置项
mystring: gfy

# 运行环境配置
spring:
  profiles:
    active: dev

student:
  id: 111
  name: stu1
  age: 21

student2: {di: 222,name: stu2,age: 22}

mylist:
  dbtype:
    - mysql
    - sqlite
    - sqlserver