server:
  port: 9090

# 一级用户自定义配置项
mystring: gfy

# 多级目录的系统配置项（数据库配置）
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/test?characterEncoding=utf-8
    username: root
    password: 111111

student:
  id: 111
  name: stu1
  age: 21

student2: {di: 222,name: stu2,age: 22}

mylist:
  dbtype:
    - mysql
    - sqlite
    - sqlserver